#!/usr/bin/env bash

set -o errexit
set -o nounset

POWERDNS_SQLITE_DB=%s/pdns.db
if [ ! -f $POWERDNS_SQLITE_DB ]; then
  cat /config/schema.sql | sqlite3 $POWERDNS_SQLITE_DB
fi
chmod 664 $POWERDNS_SQLITE_DB

ZONE=%s
if ! pdnsutil list-zone $ZONE; then
  pdnsutil create-zone $ZONE ns1.$ZONE
fi

/usr/sbin/pdns_server "$@"
